var locations = [
    "river",
    "pond",
    "lake",
    "waterfall",
    "ocean (m)",
    "ocean (m & i)",
    "ocean (i)",

    "flying",
    "flying near flowers",
    "flying near lights",
    "on trees",
    "in trees",
    "on ground",
    "on flowers",
    "on flowers white",
    "near flowers blu, bla, pu",
    "on rotten food",
    "rivers and ponds",
    "on bushes",
    "underground",
    "tree stumps",
    "snow balls",
    "on beach",
    "on palm trees",
    "flying near river",
    "on villagers",
    "under rocks",
    "flying near trash",

    "mainland & island",
    "island",
];

var sizes = [
    "N/A",
    "*Tiny", "*Small", "*Medium", "*Large", "*Very Large", "*Huge", "*Huge with fin", "*Long and thin",
    "Tiny", "Small", "Medium", "Large", "Very Large",
];

var types = [ "fish", "bug", "deepsea",];

var collectables = [
    {id:0,   have: 0, type: 0, name: "bitterling",            loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 900,    hours: [0],           months: [10, 1]                },
    {id:1,   have: 0, type: 0, name: "pale chub",             loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 200,    hours: [9, 15],       months: [0]                    },
    {id:2,   have: 0, type: 0, name: "crucian carp",          loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 120,    hours: [0],           months: [0]                    },
    {id:3,   have: 0, type: 0, name: "dace",                  loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 200,    hours: [16, 8],       months: [0]                    },
    {id:4,   have: 0, type: 0, name: "barbel steed",          loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 200,    hours: [0],           months: [0]                    },
    {id:5,   have: 0, type: 0, name: "carp",                  loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 300,    hours: [0],           months: [0]                    },
    {id:6,   have: 0, type: 0, name: "koi",                   loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 4000,   hours: [16, 8],       months: [0]                    },
    {id:7,   have: 0, type: 0, name: "goldfish",              loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 1300,   hours: [0],           months: [0]                    },
    {id:8,   have: 0, type: 0, name: "popeyed goldfish",      loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 1300,   hours: [9, 15],       months: [0]                    },
    {id:9,   have: 0, type: 0, name: "killifish",             loc: 1,  rain: 0, size: 1,  main: 1, island: 0,   price: 300,    hours: [0],           months: [3, 7]                 },
    {id:10,  have: 0, type: 0, name: "crawfish",              loc: 1,  rain: 0, size: 2,  main: 1, island: 0,   price: 200,    hours: [0],           months: [3, 8]                 },
    {id:11,  have: 0, type: 0, name: "soft shelled turtle",   loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 3750,   hours: [16, 8],       months: [7, 8]                 },
    {id:12,  have: 0, type: 0, name: "tadpole",               loc: 1,  rain: 0, size: 1,  main: 1, island: 0,   price: 100,    hours: [0],           months: [2, 6]                 },
    {id:13,  have: 0, type: 0, name: "frog",                  loc: 1,  rain: 0, size: 1,  main: 1, island: 0,   price: 120,    hours: [0],           months: [4, 7]                 },
    {id:14,  have: 0, type: 0, name: "freshwater goby",       loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 300,    hours: [16, 8],       months: [0]                    },
    {id:15,  have: 0, type: 0, name: "loach",                 loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 300,    hours: [0],           months: [2, 4]                 },
    {id:16,  have: 0, type: 0, name: "catfish",               loc: 2,  rain: 0, size: 4,  main: 1, island: 0,   price: 800,    hours: [16, 8],       months: [4, 9]                 },
    {id:17,  have: 0, type: 0, name: "eel",                   loc: 0,  rain: 0, size: 8,  main: 1, island: 0,   price: 2000,   hours: [16, 8],       months: [5, 9]                 },
    {id:18,  have: 0, type: 0, name: "giant snakehead",       loc: 2,  rain: 0, size: 5,  main: 1, island: 0,   price: 550,    hours: [9, 15],       months: [5, 7]                 },
    {id:19,  have: 0, type: 0, name: "bluegill",              loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 120,    hours: [9, 15],       months: [0]                    },
    {id:20,  have: 0, type: 0, name: "yellow perch",          loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 240,    hours: [0],           months: [9, 2]                 },
    {id:21,  have: 0, type: 0, name: "black bass",            loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 300,    hours: [0],           months: [0]                    },
    {id:22,  have: 0, type: 0, name: "pike",                  loc: 0,  rain: 0, size: 5,  main: 1, island: 0,   price: 1800,   hours: [4, 20],       months: [8, 11]                },
    {id:23,  have: 0, type: 0, name: "pond smelt",            loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 300,    hours: [0],           months: [11, 1]                },
    {id:24,  have: 0, type: 0, name: "sweetfish",             loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 900,    hours: [0],           months: [6, 9]                 },
    {id:25,  have: 0, type: 0, name: "cherry salmon",         loc: 0,  rain: 0, size: 3,  main: 1, island: 0,   price: 1000,   hours: [0],                                   months: [2, 3, 4, 5, 8, 9, 10],  monthString: m[2] + " - " + m[5] + ", " + m[8] + " - " + m[10]},
    {id:26,  have: 0, type: 0, name: "char",                  loc: 3,  rain: 0, size: 3,  main: 1, island: 0,   price: 3800,   hours: [4, 5, 6, 7, 8, 16, 17, 18, 19, 20],   months: [2, 3, 4, 5, 8, 9, 10],  monthString: m[2] + " - " + m[5] + ", " + m[8] + " - " + m[10], hourString: h[4] + " - " + h[8] + ", " + h[16] + " - " + h[20]},
    {id:27,  have: 0, type: 0, name: "rainbow trout",         loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 800,    hours: [0],                                   months: [2, 3, 4, 5, 8, 9, 10],  monthString: m[2] + " - " + m[5] + ", " + m[8] + " - " + m[10]},
    {id:28,  have: 0, type: 0, name: "stringfish",            loc: 0,  rain: 0, size: 6,  main: 1, island: 0,   price: 15000,  hours: [16, 8],       months: [11, 1]                },
    {id:29,  have: 0, type: 0, name: "salmon",                loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 700,    hours: [0],           months: [8, 8]                 },
    {id:30,  have: 0, type: 0, name: "king salmon",           loc: 3,  rain: 0, size: 6,  main: 1, island: 0,   price: 18000,  hours: [0],           months: [8, 8]                 },
    {id:31,  have: 0, type: 0, name: "mitten crab",           loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 2000,   hours: [16, 8],       months: [8, 10]                },
    {id:32,  have: 0, type: 0, name: "guppy",                 loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 1300,   hours: [9, 15],       months: [3, 10]                },
    {id:33,  have: 0, type: 0, name: "nibble fish",           loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 1500,   hours: [9, 15],       months: [4, 8]                 },
    {id:34,  have: 0, type: 0, name: "angelfish",             loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 3000,   hours: [16, 8],       months: [4, 9]                 },
    {id:35,  have: 0, type: 0, name: "neon tetra",            loc: 0,  rain: 0, size: 1,  main: 1, island: 0,   price: 500,    hours: [9, 15],       months: [3, 10]                },
    {id:36,  have: 0, type: 0, name: "piranha",               loc: 0,  rain: 0, size: 2,  main: 1, island: 0,   price: 2500,   hours: [0, 1, 2, 3, 9, 10, 11, 12, 13, 14, 15, 21, 22, 23], months: [5, 8], hourString: h[9] + " - " + h[15] + ", " + h[21] + " - " + h[3]},
    {id:37,  have: 0, type: 0, name: "arowana",               loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 10000,  hours: [16, 8],       months: [5, 8]                 },
    {id:38,  have: 0, type: 0, name: "dorado",                loc: 0,  rain: 0, size: 5,  main: 1, island: 0,   price: 15000,  hours: [4, 20],       months: [5, 8]                 },
    {id:39,  have: 0, type: 0, name: "gar",                   loc: 2,  rain: 0, size: 6,  main: 1, island: 0,   price: 6000,   hours: [16, 8],       months: [5, 8]                 },
    {id:40,  have: 0, type: 0, name: "arapaima",              loc: 0,  rain: 0, size: 6,  main: 1, island: 0,   price: 10000,  hours: [16, 8],       months: [6, 8]                 },
    {id:41,  have: 0, type: 0, name: "saddled bichir",        loc: 0,  rain: 0, size: 4,  main: 1, island: 0,   price: 4000,   hours: [21, 3],       months: [5, 8]                 },
    {id:42,  have: 0, type: 0, name: "sea butterfly",         loc: 4,  rain: 0, size: 1,  main: 1, island: 0,   price: 1000,   hours: [0],           months: [11, 1]                },
    {id:43,  have: 0, type: 0, name: "seahorse",              loc: 5,  rain: 0, size: 1,  main: 1, island: 1,   price: 1100,   hours: [0],           months: [3, 10]                },
    {id:44,  have: 0, type: 0, name: "clownfish",             loc: 5,  rain: 0, size: 1,  main: 1, island: 1,   price: 650,    hours: [0],           months: [2, 8]                 },
    {id:45,  have: 0, type: 0, name: "surgeonfish",           loc: 5,  rain: 0, size: 2,  main: 1, island: 1,   price: 1000,   hours: [0],           months: [3, 8]                 },
    {id:46,  have: 0, type: 0, name: "butterfly fish",        loc: 5,  rain: 0, size: 2,  main: 1, island: 1,   price: 1000,   hours: [0],           months: [2, 8]                 },
    {id:47,  have: 0, type: 0, name: "nepoleonfish",          loc: 5,  rain: 0, size: 6,  main: 1, island: 1,   price: 10000,  hours: [4, 20],       months: [6, 7]                 },
    {id:48,  have: 0, type: 0, name: "zebra turkeyfish",      loc: 5,  rain: 0, size: 3,  main: 1, island: 1,   price: 400,    hours: [0],           months: [2, 10]                },
    {id:49,  have: 0, type: 0, name: "blowfish",              loc: 4,  rain: 0, size: 3,  main: 1, island: 0,   price: 125,    hours: [21, 3],       months: [10, 1]                },
    {id:50,  have: 0, type: 0, name: "puffer fish",           loc: 5,  rain: 0, size: 3,  main: 1, island: 1,   price: 240,    hours: [16, 8],       months: [2, 3, 5, 6, 7, 8],  monthString: m[2] + " - " + m[5] + ", " + m[6] + " - " + m[8]},
    {id:51,  have: 0, type: 0, name: "horse mackerel",        loc: 5,  rain: 0, size: 2,  main: 1, island: 1,   price: 150,    hours: [0],           months: [0]                    },
    {id:52,  have: 0, type: 0, name: "barred knifejaw",       loc: 5,  rain: 0, size: 3,  main: 1, island: 1,   price: 5000,   hours: [0],           months: [2, 10]                },
    {id:53,  have: 0, type: 0, name: "sea bass",              loc: 5,  rain: 0, size: 5,  main: 1, island: 1,   price: 200,    hours: [0],           months: [0]                    },
    {id:54,  have: 0, type: 0, name: "red snapper",           loc: 5,  rain: 0, size: 3,  main: 1, island: 1,   price: 3000,   hours: [0],           months: [0]                    },
    {id:55,  have: 0, type: 0, name: "dab",                   loc: 4,  rain: 0, size: 3,  main: 1, island: 0,   price: 300,    hours: [0],           months: [9, 3]                 },
    {id:56,  have: 0, type: 0, name: "olive flounder",        loc: 5,  rain: 0, size: 4,  main: 1, island: 1,   price: 800,    hours: [0],           months: [0]                    },
    {id:57,  have: 0, type: 0, name: "squid",                 loc: 5,  rain: 0, size: 3,  main: 1, island: 1,   price: 400,    hours: [0],           months: [11, 7]                },
    {id:58,  have: 0, type: 0, name: "moray eel",             loc: 5,  rain: 0, size: 5,  main: 1, island: 1,   price: 2000,   hours: [0],           months: [2, 9]                 },
    {id:59,  have: 0, type: 0, name: "ribbon eel",            loc: 6,  rain: 0, size: 8,  main: 0, island: 1,   price: 600,    hours: [0],           months: [0]                    },
    {id:60,  have: 0, type: 0, name: "football fish",         loc: 4,  rain: 0, size: 4,  main: 1, island: 0,   price: 2500,   hours: [16, 8],       months: [10, 2]                },
    {id:61,  have: 0, type: 0, name: "tuna",                  loc: 4,  rain: 0, size: 6,  main: 1, island: 0,   price: 7000,   hours: [0],           months: [10, 2]                },
    {id:62,  have: 0, type: 0, name: "blue marlin",           loc: 5,  rain: 0, size: 6,  main: 1, island: 1,   price: 10000,  hours: [0],           months: [3, 8]                 },
    {id:63,  have: 0, type: 0, name: "giant trevally",        loc: 6,  rain: 0, size: 5,  main: 0, island: 1,   price: 4500,   hours: [0],           months: [0]                    },
    {id:64,  have: 0, type: 0, name: "ray",                   loc: 5,  rain: 0, size: 5,  main: 1, island: 1,   price: 3000,   hours: [4, 20],       months: [5, 10]                },
    {id:65,  have: 0, type: 0, name: "ocean sunfish",         loc: 5,  rain: 0, size: 7,  main: 1, island: 1,   price: 4000,   hours: [4, 20],       months: [3, 8]                 },
    {id:66,  have: 0, type: 0, name: "hammerhead shark",      loc: 5,  rain: 0, size: 7,  main: 1, island: 1,   price: 8000,   hours: [16, 8],       months: [2, 8]                 },
    {id:67,  have: 0, type: 0, name: "shark",                 loc: 5,  rain: 0, size: 7,  main: 1, island: 1,   price: 15000,  hours: [16, 8],       months: [2, 8]                 },
    {id:68,  have: 0, type: 0, name: "saw shark",             loc: 5,  rain: 0, size: 7,  main: 1, island: 1,   price: 12000,  hours: [16, 8],       months: [2, 8]                 },
    {id:69,  have: 0, type: 0, name: "whale shark",           loc: 6,  rain: 0, size: 7,  main: 0, island: 1,   price: 13000,  hours: [0],           months: [0]                    },
    {id:70,  have: 0, type: 0, name: "oarfish",               loc: 4,  rain: 0, size: 6,  main: 1, island: 0,   price: 9000,   hours: [0],           months: [11, 4]                },
    {id:71,  have: 0, type: 0, name: "coelacanth",            loc: 4,  rain: 1, size: 6,  main: 1, island: 0,   price: 15000,  hours: [16, 8],       months: [0]                    },
    {id:72,  have: 0, type: 1, name: "common butterfly",      loc: 8,  rain: 0, size: 0,  main: 1, island: 0,   price: 90,     hours: [4, 18],       months: [2, 3, 4, 5, 8], monthString: m[2] + " - " + m[5] + " - " + m[8]},
    {id:73,  have: 0, type: 1, name: "yellow butterfly",      loc: 8,  rain: 0, size: 0,  main: 1, island: 0,   price: 90,     hours: [6, 15],       months: [2, 3, 4, 5, 8], monthString: m[2] + " - " + m[5] + " - " + m[8]},
    {id:74,  have: 0, type: 1, name: "tiger butterfly",       loc: 8,  rain: 0, size: 0,  main: 1, island: 0,   price: 160,    hours: [8, 18],       months: [2, 8]                 },
    {id:75,  have: 0, type: 1, name: "peacock butterfly",     loc: 15,  rain: 0, size: 0,  main: 1, island: 0,   price: 220,    hours: [4, 18],       months: [2, 8]                 },
    {id:76,  have: 0, type: 1, name: "monarch butterfly",     loc: 7,  rain: 0, size: 0,  main: 1, island: 1,   price: 140,    hours: [9, 16],       months: [3, 8, 9, 10],   monthString: m[3] + ", " + m[8] + " - " + m[10]},
    {id:77,  have: 0, type: 1, name: "emperor butterfly",     loc: 7,  rain: 0, size: 0,  main: 1, island: 1,   price: 2500,   hours: [20, 6],       months: [3, 5, 6, 7, 8], monthString: m[3] + ", " + m[5] + " - " + m[8]},
    {id:78,  have: 0, type: 1, name: "agrias butterfly",      loc: 8,  rain: 0, size: 0,  main: 1, island: 1,   price: 3000,   hours: [8, 16],       months: [3, 5, 6, 7, 8], monthString: m[3] + ", " + m[5] + " - " + m[8]},
    {id:79,  have: 0, type: 1, name: "raja brooke butterfly", loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 2500,   hours: [8, 16],       months: [4, 8]                 },
    {id:80,  have: 0, type: 1, name: "birdwing butterfly",    loc: 7,  rain: 0, size: 0,  main: 1, island: 1,   price: 4000,   hours: [8, 15],       months: [3, 5, 6, 7, 8], monthString: m[3] + ", " + m[5] + " - " + m[8]},
    {id:81,  have: 0, type: 1, name: "moth",                  loc: 9,  rain: 0, size: 0,  main: 1, island: 0,   price: 60,     hours: [19, 3],       months: [4, 8]                 },
    {id:82,  have: 0, type: 1, name: "oak silk moth",         loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 1200,   hours: [19, 3],       months: [5, 8]                 },
    {id:83,  have: 0, type: 1, name: "honeybee",              loc: 8,  rain: 0, size: 0,  main: 1, island: 0,   price: 100,    hours: [8, 16],       months: [2, 6]                 },
    {id:84,  have: 0, type: 1, name: "bee",                   loc: 11, rain: 0, size: 0,  main: 1, island: 0,   price: 2500,   hours: [0],           months: [0]                    },
    {id:85,  have: 0, type: 1, name: "long locust",           loc: 12, rain: 0, size: 0,  main: 1, island: 1,   price: 200,    hours: [8, 18],       months: [3, 10]                },
    {id:86,  have: 0, type: 1, name: "migratory locust",      loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 600,    hours: [8, 18],       months: [7, 10]                },
    {id:87,  have: 0, type: 1, name: "rice grasshopper",      loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 400,    hours: [8, 18],       months: [7, 9]                 },
    {id:88,  have: 0, type: 1, name: "mantis",                loc: 13, rain: 0, size: 0,  main: 1, island: 0,   price: 430,    hours: [8, 16],       months: [3, 10]                },
    {id:89,  have: 0, type: 1, name: "orchid mantis",         loc: 14, rain: 0, size: 0,  main: 1, island: 0,   price: 2400,   hours: [8, 18],       months: [3, 10]                },
    {id:90,  have: 0, type: 1, name: "brown cicada",          loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 200,    hours: [8, 16],       months: [6, 7]                 },
    {id:91,  have: 0, type: 1, name: "robust cicada",         loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 300,    hours: [8, 16],       months: [6, 7]                 },
    {id:92,  have: 0, type: 1, name: "giant cicada",          loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 500,    hours: [8, 16],       months: [6, 7]                 },
    {id:93,  have: 0, type: 1, name: "walker cicada",         loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 400,    hours: [8, 16],       months: [6, 8]                 },
    {id:94,  have: 0, type: 1, name: "evening cicada",        loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 550,    hours: [16, 18],      months: [6, 7]                 },
    {id:95,  have: 0, type: 1, name: "cicada shell",          loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 100,    hours: [0],           months: [6, 7]                 },
    {id:96,  have: 0, type: 1, name: "latern fly",            loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 1800,   hours: [16, 7],       months: [5, 8]                 },
    {id:97,  have: 0, type: 1, name: "red dragonfly",         loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 80,     hours: [8, 18],       months: [8, 9]                 },
    {id:98,  have: 0, type: 1, name: "darner dragonfly",      loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 200,    hours: [8, 16],       months: [5, 7]                 },
    {id:99,  have: 0, type: 1, name: "banded drangonfly",     loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 4500,   hours: [8, 16],       months: [6, 7]                 },
    {id:100, have: 0, type: 1, name: "petaltail dragonfly",   loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 8000,   hours: [17, 18],      months: [7, 9]                 },
    {id:101, have: 0, type: 1, name: "ant",                   loc: 16, rain: 0, size: 0,  main: 1, island: 0,   price: 80,     hours: [0],           months: [0]                    },
    {id:102, have: 0, type: 1, name: "pondskater",            loc: 17, rain: 0, size: 0,  main: 1, island: 0,   price: 130,    hours: [8, 18],       months: [4, 8]                 },
    {id:103, have: 0, type: 1, name: "diving beetle",         loc: 17, rain: 0, size: 0,  main: 1, island: 0,   price: 800,    hours: [8, 16],       months: [4, 8]                 },
    {id:104, have: 0, type: 1, name: "stinkbug",              loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 120,    hours: [0],           months: [3, 9]                 },
    {id:105, have: 0, type: 1, name: "snail",                 loc: 18, rain: 1, size: 0,  main: 1, island: 0,   price: 250,    hours: [0],           months: [3, 8]                 },
    {id:106, have: 0, type: 1, name: "cricket",               loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 160,    hours: [17, 7],       months: [8, 10]                },
    {id:107, have: 0, type: 1, name: "bell cricket",          loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 430,    hours: [17, 7],       months: [8, 9]                 },
    {id:108, have: 0, type: 1, name: "grasshopper",           loc: 12, rain: 0, size: 0,  main: 1, island: 1,   price: 160,    hours: [8, 17],       months: [6, 8]                 },
    {id:109, have: 0, type: 1, name: "mole cricket",          loc: 19, rain: 0, size: 0,  main: 1, island: 0,   price: 280,    hours: [0],           months: [10, 4]                },
    {id:110, have: 0, type: 1, name: "walking leaf",          loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 600,    hours: [8, 16],       months: [6, 8]                 },
    {id:111, have: 0, type: 1, name: "walking stick",         loc: 10, rain: 0, size: 0,  main: 1, island: 0,   price: 600,    hours: [4, 18],       months: [3, 6, 7, 8, 9, 10], monthString: m[3] + ", " + m[6] + " - " + m[10]},
    {id:112, have: 0, type: 1, name: "bagworm",               loc: 11, rain: 0, size: 0,  main: 1, island: 0,   price: 300,    hours: [0],           months: [9, 1]                 },
    {id:113, have: 0, type: 1, name: "ladybug",               loc: 13, rain: 0, size: 0,  main: 1, island: 0,   price: 200,    hours: [8, 16],       months: [2, 3, 4, 5, 9], monthString: m[2] + " - " + m[5] + ", " + m[9]},
    {id:114, have: 0, type: 1, name: "violin beetle",         loc: 20, rain: 0, size: 0,  main: 1, island: 0,   price: 260,    hours: [4, 18],       months: [5, 8, 9, 10], monthString: m[5] + ", " + m[8] + " - " + m[10]},
    {id:115, have: 0, type: 1, name: "longhorn beetle",       loc: 20, rain: 0, size: 0,  main: 1, island: 1,   price: 260,    hours: [10, 17],      months: [6, 7]                 },
    {id:116, have: 0, type: 1, name: "tiger beetle",          loc: 12, rain: 0, size: 0,  main: 1, island: 1,   price: 1500,   hours: [8, 22],       months: [2, 9]                 },
    {id:117, have: 0, type: 1, name: "dung beetle",           loc: 21, rain: 0, size: 0,  main: 1, island: 0,   price: 1800,   hours: [17, 7],       months: [11, 1]                },
    {id:118, have: 0, type: 1, name: "wharf roach",           loc: 22, rain: 0, size: 0,  main: 1, island: 1,   price: 200,    hours: [0],           months: [0]                    },
    {id:119, have: 0, type: 1, name: "hermit crab",           loc: 22, rain: 0, size: 0,  main: 0, island: 1,   price: 1000,   hours: [19, 7],       months: [0]                    },
    {id:120, have: 0, type: 1, name: "firefly",               loc: 24, rain: 0, size: 0,  main: 1, island: 0,   price: 300,    hours: [19, 3],       months: [5, 5]                 },
    {id:121, have: 0, type: 1, name: "fruit beetle",          loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 100,    hours: [0],           months: [3, 6, 7, 8], monthString: m[3] + ", " + m[6] + " - " + m[8]},
    {id:122, have: 0, type: 1, name: "scarab beetle",         loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 6000,   hours: [23, 7],       months: [6, 7]                 },
    {id:123, have: 0, type: 1, name: "jewel beetle",          loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 2400,   hours: [8, 16],       months: [3, 6, 7],    monthString: m[3] + ", " + m[6] + ", " + m[7]},
    {id:124, have: 0, type: 1, name: "miyama stag",           loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 1000,   hours: [0],           months: [3, 6, 7],    monthString: m[3] + ", " + m[6] + ", " + m[7]},
    {id:125, have: 0, type: 1, name: "saw stag",              loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 2000,   hours: [0],           months: [3, 6, 7],    monthString: m[3] + ", " + m[6] + ", " + m[7]},
    {id:126, have: 0, type: 1, name: "giant stag",            loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 10000,  hours: [23, 7],       months: [6, 7]                 },
    {id:127, have: 0, type: 1, name: "rainbow stag",          loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 10000,  hours: [17, 7],       months: [3, 5, 6, 7, 8], monthString: m[3] + ", " + m[5] + ", " + m[6] + " - " + m[8]},
    {id:128, have: 0, type: 1, name: "cyclommatus stag",      loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 8000,   hours: [17, 7],       months: [2, 3, 5, 6, 7], monthString: m[2] + ", " + m[3] + ", " + m[5] + " - " + m[7]},
    {id:129, have: 0, type: 1, name: "golden stag",           loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 12000,  hours: [17, 7],       months: [3, 5, 6, 7], monthString: m[3] + " - " + m[5] + ", " + m[6] + ", " + m[7]},
    {id:130, have: 0, type: 1, name: "horned dynastid",       loc: 10, rain: 0, size: 0,  main: 1, island: 1,   price: 1350,   hours: [19, 7],       months: [3, 5, 6, 7], monthString: m[3] + " - " + m[5] + ", " + m[6] + ", " + m[7]},
    {id:131, have: 0, type: 1, name: "horned atlas",          loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 8000,   hours: [17, 7],       months: [3, 5, 6, 7], monthString: m[3] + " - " + m[5] + ", " + m[6] + ", " + m[7]},
    {id:132, have: 0, type: 1, name: "horned elephant",       loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 8000,   hours: [17, 7],       months: [3, 5, 6, 7], monthString: m[3] + " - " + m[5] + ", " + m[6] + ", " + m[7]},
    {id:133, have: 0, type: 1, name: "horned hercules",       loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 12000,  hours: [17, 7],       months: [3, 5, 6, 7], monthString: m[3] + " - " + m[5] + ", " + m[6] + ", " + m[7]},
    {id:134, have: 0, type: 1, name: "goliath beetle",        loc: 23, rain: 0, size: 0,  main: 1, island: 1,   price: 6000,   hours: [17, 7],       months: [5, 8]                 },
    {id:135, have: 0, type: 1, name: "flea",                  loc: 25, rain: 0, size: 0,  main: 1, island: 0,   price: 70,     hours: [0],           months: [2, 10]                },
    {id:136, have: 0, type: 1, name: "pill bug",              loc: 16, rain: 0, size: 0,  main: 1, island: 0,   price: 250,    hours: [0],           months: [0]                    },
    {id:137, have: 0, type: 1, name: "mosquito",              loc: 7,  rain: 0, size: 0,  main: 1, island: 0,   price: 130,    hours: [17, 3],       months: [5, 8]                 },
    {id:138, have: 0, type: 1, name: "fly",                   loc: 27, rain: 0, size: 0,  main: 1, island: 0,   price: 60,     hours: [0],           months: [0]                    },
    {id:139, have: 0, type: 1, name: "house centipede",       loc: 26, rain: 0, size: 0,  main: 1, island: 0,   price: 250,    hours: [19, 7],       months: [7, 9]                 },
    {id:140, have: 0, type: 1, name: "centipede",             loc: 26, rain: 0, size: 0,  main: 1, island: 0,   price: 300,    hours: [16, 22],      months: [5, 1]                 },
    {id:141, have: 0, type: 1, name: "spider",                loc: 11, rain: 0, size: 0,  main: 1, island: 0,   price: 300,    hours: [0],           months: [2, 9]                 },
    {id:142, have: 0, type: 1, name: "tarantula",             loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 8000,   hours: [19, 3],       months: [5, 7]                 },
    {id:143, have: 0, type: 1, name: "scorpion",              loc: 12, rain: 0, size: 0,  main: 1, island: 0,   price: 8000,   hours: [19, 3],       months: [6, 8]                 },
    {id:144, have: 0, type: 2, name: "seaweed",               loc: 28, rain: 0, size: 12, main: 1, island: 1,   price: 200,    hours: [0],           months: [10, 6]                },
    {id:145, have: 0, type: 2, name: "sea grapes",            loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 600,    hours: [0],           months: [3, 5, 6, 7, 8], monthString: m[3] + ", " + m[5] + " - " + m[8]},
    {id:146, have: 0, type: 2, name: "sea urchin",            loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 800,    hours: [0],           months: [3, 8]                 },
    {id:147, have: 0, type: 2, name: "acorn barnacle",        loc: 28, rain: 0, size: 9,  main: 1, island: 1,   price: 200,    hours: [0],           months:  [0]                   },
    {id:148, have: 0, type: 2, name: "oyster",                loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 400,    hours: [0],           months: [8, 1]                 },
    {id:149, have: 0, type: 2, name: "turban shell",          loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 300,    hours: [16, 8],       months: [7, 4]                 },
    {id:150, have: 0, type: 2, name: "abalone",               loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 400,    hours: [16, 8],       months: [0]                    },
    {id:151, have: 0, type: 2, name: "ear shell",             loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 300,    hours: [16, 8],       months: [0]                    },
    {id:152, have: 0, type: 2, name: "clam",                  loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 400,    hours: [0],           months: [8, 3]                 },
    {id:153, have: 0, type: 2, name: "pearl oyster",          loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 1600,   hours: [0],           months: [0]                    },
    {id:154, have: 0, type: 2, name: "scallop",               loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 1000,   hours: [0],           months: [0]                    },
    {id:155, have: 0, type: 2, name: "sea anemone",           loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 100,    hours: [0],           months: [0]                    },
    {id:156, have: 0, type: 2, name: "sea star",              loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 100,    hours: [0],           months: [0]                    },
    {id:157, have: 0, type: 2, name: "sea cucumber",          loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 150,    hours: [0],           months: [10, 3]                },
    {id:158, have: 0, type: 2, name: "sea slug",              loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 200,    hours: [0],           months: [0]                    },
    {id:159, have: 0, type: 2, name: "flatworm",              loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 200,    hours: [16, 8],       months: [5, 8]                 },
    {id:160, have: 0, type: 2, name: "mantis shrimp",         loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 1250,   hours: [16, 8],       months: [0]                    },
    {id:161, have: 0, type: 2, name: "sweet shrimp",          loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 650,    hours: [16, 8],       months: [8, 1]                 },
    {id:162, have: 0, type: 2, name: "tiger prawn",           loc: 28, rain: 0, size: 10, main: 1, island: 1,   price: 1600,   hours: [16, 8],       months: [5, 8]                 },
    {id:163, have: 0, type: 2, name: "spiny lobster",         loc: 28, rain: 0, size: 12, main: 1, island: 1,   price: 3000,   hours: [21, 3],       months: [8, 11]                },
    {id:164, have: 0, type: 2, name: "lobster",               loc: 28, rain: 0, size: 12, main: 1, island: 1,   price: 2500,   hours: [0],           months: [0]                    },
    {id:165, have: 0, type: 2, name: "snow crab",             loc: 28, rain: 0, size: 12, main: 1, island: 1,   price: 4000,   hours: [0],           months: [10, 3]                },
    {id:166, have: 0, type: 2, name: "horsehair crab",        loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 4000,   hours: [0],           months: [10, 3]                },
    {id:167, have: 0, type: 2, name: "red king crab",         loc: 28, rain: 0, size: 12, main: 1, island: 1,   price: 6000,   hours: [0],           months: [10, 2]                },
    {id:168, have: 0, type: 2, name: "spider crab",           loc: 28, rain: 0, size: 13, main: 1, island: 1,   price: 10000,  hours: [0],           months: [2, 3]                 },
    {id:169, have: 0, type: 2, name: "octopus",               loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 1000,   hours: [0],           months: [0, 2, 3, 4, 5, 6, 8, 9, 10, 11], monthString: m[0] + ", " + m[2] + " - " + m[11]},
    {id:170, have: 0, type: 2, name: "spotted garden eel",    loc: 29, rain: 0, size: 10, main: 0, island: 1,   price: 600,    hours: [0],           months: [0]                    },
    {id:171, have: 0, type: 2, name: "chambered nautilus",    loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 900,    hours: [0],           months: [0]                    },
    {id:172, have: 0, type: 2, name: "horseshoe crab",        loc: 28, rain: 0, size: 11, main: 1, island: 1,   price: 1500,   hours: [21, 3],       months: [6, 8]                 },
    {id:173, have: 0, type: 2, name: "giant isopod",          loc: 29, rain: 0, size: 11, main: 0, island: 1,   price: 9000,   hours: [0],           months: [0]                    },
];
